# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alliance for Corporate Transparency
description: The Alliance for Corporate Transparency is three-year research project that brings together leading civil society organisations and experts with the aim of analysing the corporate disclosure on sustainability issues by the 1000 largest companies operating in the EU and providing evidence-based recommendations for legislative changes.
baseurl: "" # the subpath of your site, e.g. /blog
email:
handle:
long_handle:

# default permalink for blog posts
permalink: news/:title.html

collections:
  report-2018:
    output: true
    permalink: /report-2018/:path.html
  static_data:
    output: true
  pages:
    permalink: /pages/:path.html
    output: true
  database:
    output: true
    permalink: /database/:path.html

# Analytics
ga_id:
inspectlet_id:

# report URLS 2018
url_report2018: /report-2018/
url_report2018_pdf: 2018_Research_Report_Alliance_Corporate_Transparency.pdf
companies_all: 105
companies_energy: 38
companies_health: 33
companies_ict: 34

# report URLS 2019
url_report2019: /database/
url_report2019_pdf: "2019_Research_Report _Alliance_for_Corporate_Transparency.pdf"

# report URLS 2020
url_report2020: /database/
url_report2020_pdf: Research_Report_EUKI_2020.pdf

url_materiality_matrix: 2019_Materiality-matrix.pdf
url_newsletter: http://eepurl.com/dJPBjQ

# Social handlers
twitter_url: https://twitter.com/
github_url: https://github.com/

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile', '_config.yml', 'config', 'bin']

assets:
  digest: false
  sources:
    - _assets/posts
  features:
    automatic_img_size: false

sources:
  - _assets/pdf

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets
