name: Jekyll build and deploy to FTP

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: helaili/jekyll-action@2.0.5
