name: Jekyll build and deploy to FTP

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout source branch for building Pages
          uses: actions/checkout@v1
        - name: Make build destination directory
          run: mkdir -vp ~/www/repository-name
        - name: Jekyll Build
          uses: gha-utilities/jekyll-build@v0.0.5
