name: Jekyll build and deploy to FTP

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: jekyll build
        uses: mbursi/jekyll-build-only-action@v1.0.0
