name: Jekyll build and deploy to FTP

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: tidalmigrations/jekyll-build-action@master
  robots:
    needs: jekyll
    - name: delete robots
      run: rm /github/workspace/_site/robots.txt
