name: Jekyll build and deploy to FTP

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site.
      uses: fabacab/jekyll-builder-for-github-pages-action@v1
      with:
        jekyll_build_opts: --future
        pre_build_commands: gem install bundler
